CREATE OR REPLACE PROCEDURE runcommand (command IN VARCHAR2)
AUTHID CURRENT_USER
IS
BEGIN
    EXECUTE IMMEDIATE command;
END;

CREATE OR REPLACE PROCEDURE PR_DB1_SAVE_LOG 
(p_log IN TDB3_LOG%ROWTYPE)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO TDB3_LOG VALUES p_log;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE PR_DB1_SAVE_NOTIFY
(p_notif IN TDB4_NOTIF_PRODUTO%ROWTYPE)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO TDB4_NOTIF_PRODUTO VALUES p_notif;
    COMMIT;
END;