-- Trigger que salva um log quando a quantidade de um produto cai abaixo de 10
CREATE OR REPLACE TRIGGER TR_DB1_LOW_PRODUCT
AFTER UPDATE OF PO_ESTOQUE ON TDB2_PRODUTO
FOR EACH ROW
    WHEN (NEW.PO_ESTOQUE <= 10)
DECLARE
    v_log TDB3_LOG%ROWTYPE;    
BEGIN
    SELECT USER INTO v_log.LG_USUARIO FROM DUAL;
    v_log.LG_ID_ENTIDADE := :NEW.PO_ID;
    v_log.LG_NOME_ENTIDADE := 'TDB2_PRODUTO';
    v_log.LG_DATA_MODIFICACAO := SYSDATE;
    v_log.LG_ANTES_ALTERACAO := :OLD.PO_ESTOQUE;
    v_log.LG_DEPOIS_ALTERACAO := :NEW.PO_ESTOQUE;
    PR_DB1_SAVE_LOG(v_log);
END;